### ISSUE TITLE
KeyLayoutAutoSwitch 2.0 gets misled by Skype official client and Spotify desktop client

### ISSUE THREAD

**Issue by ablazhov** [AlexVallat/KeyLayoutAutoSwitch#11]
KeyLayoutAutoSwitch 2.0 misinterprets "Skype for Desktop" and "Spotify for PC" for being Crome and tries to switch keyboard layouts accordingly. I believe this is because both Skype and Spotify are based on Electron, which by itself is based on Chromium (Chrome) and besides they both start with an S ;-).
Interestingly enough Viber is also Electron based but it does not confuse KeyLayoutAutoSwitch 2.0. Maybe Rakuten made better job of hiding the framework.

**Comment by AlexVallat** [comment]
Hmm, yes, I see the problem. Not really sure what I can do about this, as these electron apps look identical to other Chromium based apps such as Opera or Brave, which certainly should be treated as browsers. They all present themselves as a Chrome_WidgetWin top level window with a Chrome_RenderWidgetHostHWND child.

Then you've got sort of half-way things like Battle.net or Steam which are not really web browsers, but sometimes kind-of are, when you are browsing pages in them.

Possibly the only way to solve this is allow a user configurable allow list or block list to specify processes which should be ignored or not, but this isn't always easy to manage, particularly for a less technical user who might not know the process name.

**Comment by ablazhov** [comment]
> 
> 
> Possibly the only way to solve this is allow a user configurable allow list or block list to specify processes which should be ignored or not, but this isn't always easy to manage, particularly for a less technical user who might not know the process name.

I don't know, maybe putting such configuration options in a slightly hidden UI would help unexperienced users not getting confused... Or just use an external configuration file and let users self-populate the ignore list.

It turned out Viber is not electron but Qt based, if I'm not mistaken. Other notorious electron based applications are StreamLabs OBS Studio, M$ Teams, Signal, Discord, WhatsApp etc.
https://en.wikipedia.org/wiki/Electron_(software_framework)
https://wiredelta.com/10-most-popular-electron-apps-2019/

I replaced these class ID strings ("Chrome_WidgetWin" & "Chrome_RenderWidgetHostHWND") in Skype and Spotify binaries with random characters and Your app now dosn't try to switch keyboard layouts when I activate those applications, but this is just a temporary workaround for more experienced users.

**Comment by AlexVallat** [comment]
I have implemented a process allow-list of brave, chrome, opera, firefox, gecko. This can be overridden by editing `%APPDATA%\KeyLayoutAutoSwitch\Rules.xml` adding or removing `<Process>` entries under `<BrowserProcessNameRule>`. If that element doesn't exist yet then just make any change to the config in the UI to make it re-save the xml file with the default entries. Removing the entire `<BrowserProcessNameRule>` element will revert to the default allow-list.

Could you give the attached updated 2.1 a try and let me know if it resolves the issue for you, before I release?
[KeyLayoutAutoSwitch.zip](https://github.com/AlexVallat/KeyLayoutAutoSwitch/files/6948900/KeyLayoutAutoSwitch.zip)

**Comment by ablazhov** [comment]
I hope I'm not too unobjective here but it appears that the new functionality works as intended.
I understand that the file extension ".exe" is not needed? What about case-sensitivity?

**Comment by AlexVallat** [comment]
Not case sensitive, and yes, no .exe at the end. Thanks for letting me know, I'll test a bit more myself too and hopefully release today or tomorrow.
