### ISSUE TITLE
Bulgarian translation - attached

### ISSUE THREAD

**Issue by ablazhov** [AlexVallat/KeyLayoutAutoSwitch#6]
I'm not sure how to use the Pull request method, so I decided to attach a zip file here.
[bg.zip](https://github.com/AlexVallat/KeyLayoutAutoSwitch/files/5684556/bg.zip)

**Comment by AlexVallat** [comment]
That's great, thanks! Missing one for the new IconMenuAddRule "Add Site Rule...", could you give me a translation for that too please?

**Comment by ablazhov** [comment]
Добави правило за сайт...
